'use client';
import { useEffect, useMemo, useState } from 'react';
import { dashboardApi, type CalendarApiResponse } from '@/lib/client-api';
import type { CalendarEvent } from '@/lib/calendar';
import { daysUntil, groupCalendarEvents } from '@/lib/calendar-view';
import { classifyRepositoryItems, type RepositoryItem } from '@/lib/repository';
import type { DashboardBundle } from '@/lib/results';

const initialCalendar:CalendarApiResponse={configured:false,state:'unconfigured',calendarId:'primary',timezone:'Asia/Seoul',range:{days:14,timeMin:'',timeMax:''},items:[]};
const pageMeta:Record<string,[string,string]>={home:['Korea Necessary Labour Thesis Dashboard','GitHub 연구 데이터와 Google Calendar를 한 화면에서'],research:['Research','연구 파이프라인 · 질문 · 결정사항'],results:['Results','GitHub 결과 데이터 · 추이 · 분해 · 검증'],literature:['Literature','GitHub Literature 디렉터리 · 로컬 파일 열기'],wiki:['Wiki','GitHub Wiki 문서 인덱스'],tasks:['Tasks','연구 작업 현황'],files:['Files','GitHub 파일 목록 · 로컬 mirror 열기'],ai:['AI','연구 프롬프트 런처'],settings:['Settings','repo 경로와 로컬 브리지 설정']};
const nav=['home','research','results','literature','wiki','tasks','files','ai','settings'];
const labels:Record<string,string>={home:'⌂ Home',research:'⌕ Research',results:'▥ Results',literature:'▤ Literature',wiki:'▧ Wiki',tasks:'☑ Tasks',files:'▣ Files',ai:'✦ AI',settings:'⚙ Settings'};

export default function Page(){
 const [page,setPage]=useState('home'); const [tree,setTree]=useState<RepositoryItem[]>([]); const [calendar,setCalendar]=useState<CalendarApiResponse>(initialCalendar); const [dashboard,setDashboard]=useState<DashboardBundle>({source:'empty',necessaryLabour:null,decomposition:null,validation:null}); const [ghConfigured,setGhConfigured]=useState(false); const [errors,setErrors]=useState<string[]>([]); const [toast,setToast]=useState(''); const [query,setQuery]=useState('');
 useEffect(()=>{(async()=>{const results=await Promise.allSettled([dashboardApi.tree(),dashboardApi.calendar(),dashboardApi.results()]);const [treeResult,calendarResult,dashboardResult]=results;if(treeResult.status==='fulfilled'){setGhConfigured(treeResult.value.configured);setTree(treeResult.value.items||[]);if(treeResult.value.error)setErrors(x=>[...x,treeResult.value.error!]);}else setErrors(x=>[...x,treeResult.reason instanceof Error?treeResult.reason.message:'GitHub request failed']);if(calendarResult.status==='fulfilled')setCalendar(calendarResult.value);else setCalendar({...initialCalendar,state:'error',errorCode:'network_error'});if(dashboardResult.status==='fulfilled')setDashboard(dashboardResult.value);})()},[]);
 function pop(s:string){setToast(s);setTimeout(()=>setToast(''),1700)}
 async function openLocal(path:string){const base=process.env.NEXT_PUBLIC_LOCAL_BRIDGE_URL||'http://127.0.0.1:38471';const token=localStorage.getItem('thesisBridgeToken')||'';try{const r=await fetch(base+'/open',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path,token})});const d=await r.json();if(!r.ok)throw new Error(d.error||'bridge error');pop('로컬 파일을 열었어');}catch(e){pop('로컬 브리지 확인 필요')}}
 const groups=useMemo(()=>classifyRepositoryItems(tree),[tree]);
 const files=useMemo(()=>tree.filter(x=>x.type==='blob').filter(x=>x.path.toLocaleLowerCase().includes(query.toLocaleLowerCase())).slice(0,120),[tree,query]);
 const literature=groups.literature.filter(x=>x.path.toLocaleLowerCase().includes(query.toLocaleLowerCase())&&/\.(pdf|docx?|md)$/i.test(x.path)).slice(0,120);
 const wiki=groups.wiki.filter(x=>/\.md$/i.test(x.path)).slice(0,120);
 const schedule=useMemo(()=>groupCalendarEvents(calendar.items),[calendar.items]);
 return <div className="shell">
  <aside className="sidebar"><div className="brand"><div className="logo">M</div><div><h1>Master Thesis OS</h1><p>Research dashboard v0.1</p></div></div><nav className="nav">{nav.map(n=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}>{labels[n]}</button>)}</nav></aside>
  <main className="main"><div className="top"><div><h2>{pageMeta[page][0]}</h2><p>{pageMeta[page][1]}</p></div><div className="badges"><div className="badge">GitHub {ghConfigured?'● connected':'○ mock'}</div><div className="badge">Calendar {calendar.state==='ready'||calendar.state==='empty'?'● connected':'○ unavailable'}</div><div className="badge">v0.1</div></div></div>
  {errors.length>0&&<div className="error" style={{marginBottom:14}}>{errors[0]}</div>}
  <section className={'page '+(page==='home'?'active':'')}><div className="kpis"><Kpi label="Research files" value={ghConfigured?String(tree.filter(x=>x.type==='blob').length):'—'} sub="GitHub repository"/><Kpi label="Upcoming events" value={calendar.configured?String(calendar.items.length):'—'} sub="Today + next 14 days"/><Kpi label="Current focus" value="Interpretation" sub="2015→2020"/><Kpi label="Latest pipeline" value="Validated" sub="Necessary labour"/></div><div className="grid3"><CalendarCard title="Today" events={schedule.today} calendar={calendar}/><CalendarCard title="Upcoming" events={schedule.upcoming.slice(0,6)} calendar={calendar}/><Card title="Next Deadline" right="Deadline / Meeting">{schedule.nextDeadline?<div className="event"><b>{schedule.nextDeadline.title}</b><small>{formatCalendarEvent(schedule.nextDeadline)} · D-{daysUntil(schedule.nextDeadline)}</small>{schedule.nextDeadline.location&&<small>{schedule.nextDeadline.location}</small>}</div>:<CalendarState calendar={calendar}/>}</Card></div><div className="grid2" style={{marginTop:14}}><Card title="Research Status" right="v0.1"><Status n="Data" p={100}/><Status n="Methodology" p={90}/><Status n="Calculation" p={100}/><Status n="Validation" p={90}/><Status n="Interpretation" p={60}/><Status n="Writing" p={30}/></Card><Card title="Recent repo files" right={ghConfigured?'Live':'Mock'}>{files.slice(0,6).map(f=><div className="todo" key={f.path}>{f.path}</div>)}{!ghConfigured&&<div className="empty">.env.local에 GitHub 설정을 넣으면 실시간으로 바뀜.</div>}</Card></div><div className="card section" style={{marginTop:14}}><div className="head"><h3>Research Pipeline</h3><span>GitHub = source of truth</span></div><div className="pipeline">{['Raw Data','Sector Mapping','Labour Time','Consumption Basket','Necessary Labour','Decomposition','Interpretation'].map((s,i)=><span key={s} style={{display:'contents'}}><div className={'stage '+(s==='Necessary Labour'?'active':'')}><b>{s}</b><small>{s==='Interpretation'?'In progress':'Tracked'}</small></div>{i<6&&<span className="arrow">→</span>}</span>)}</div></div></section>
  <section className={'page '+(page==='research'?'active':'')}><div className="card section"><div className="head"><h3>Research Pipeline</h3><span>repo-backed structure</span></div><div className="pipeline">{['Raw Data','Sector Mapping','Labour Time','Consumption Basket','Necessary Labour','Decomposition','Interpretation'].map((s,i)=><span key={s} style={{display:'contents'}}><div className={'stage '+(s==='Necessary Labour'?'active':'')}><b>{s}</b><small>{i<5?'Validated':'Review'}</small></div>{i<6&&<span className="arrow">→</span>}</span>)}</div></div><div className="grid2" style={{marginTop:14}}><Card title="Research Questions" right="Current"><div className="note"><b>Main</b><br/>한국의 필요노동은 2010–2020년 동안 어떻게 변화했는가?</div><div className="note" style={{marginTop:9}}><b>Sub</b><br/>변화는 소비구성과 생산조건 중 무엇에 의해 설명되는가?</div></Card><Card title="Decision Log" right="GitHub Wiki"><div className="todo">2020 기준 불변가격 중심 분석</div><div className="todo">산업별 실제근로시간 채택</div><div className="todo">바스켓·투하노동량 2요인 분해</div></Card></div></section>
  <section className={'page '+(page==='results'?'active':'')}><ResultsPanel dashboard={dashboard}/></section>
  <section className={'page '+(page==='literature'?'active':'')}><div className="toolbar"><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Literature 파일 검색"/></div><div className="litgrid">{literature.map(f=><div className="card paper" key={f.path}><h4>{basename(f.path)}</h4><span className="tag blue">GitHub</span><p>{f.path}</p><div className="actions"><button className="mini" onClick={()=>openLocal(f.path)}>Open Local</button></div></div>)}{literature.length===0&&<div className="card empty">GitHub의 Literature 폴더가 연결되면 문헌 파일이 자동으로 표시돼.</div>}</div></section>
  <section className={'page '+(page==='wiki'?'active':'')}><div className="wikigrid">{wiki.slice(0,60).map(f=><div className="card wikicard" key={f.path}><b style={{fontSize:12}}>{basename(f.path)}</b><div className="muted" style={{fontSize:9,marginTop:5}}>{f.path}</div><button className="mini" style={{marginTop:9}} onClick={()=>openLocal(f.path)}>Open Local</button></div>)}{wiki.length===0&&<div className="card empty">GitHub의 <code>wiki/</code> markdown 파일이 여기에 표시된다.</div>}</div></section>
  <section className={'page '+(page==='tasks'?'active':'')}><div className="grid2"><Card title="Doing" right="Research"><div className="todo">2015→2020 결과 해석 보강</div><div className="todo">중간발표 결과 슬라이드 검토</div></Card><Card title="Blocked" right="Need support"><div className="todo">생산조건 효과 설명 근거 보강</div></Card></div></section>
  <section className={'page '+(page==='files'?'active':'')}><div className="toolbar"><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="GitHub repo 파일 검색"/></div><div className="filegrid">{files.map(f=><div className="card filecard" key={f.path}><div className="fileicon">{ext(f.path)}</div><div className="grow"><h4>{basename(f.path)}</h4><p>{f.path}</p></div><div className="actions"><button className="mini" onClick={()=>openLocal(f.path)}>Open Local</button></div></div>)}{files.length===0&&<div className="card empty">GitHub 설정을 넣으면 repo 파일이 표시돼.</div>}</div></section>
  <section className={'page '+(page==='ai'?'active':'')}><div className="aigrid">{[['Review Logic','Review the thesis logic using methodology, decisions, and current findings.'],['Interpret Results','Interpret changes in necessary labour and separate consumption and production-condition effects.'],['Audit Code','Audit code against methodology and current result files.'],['Update Wiki','Update the research wiki while preserving methodology/findings/decisions boundaries.']].map(([t,p])=><div className="card aicard" key={t}><h4>{t}</h4><textarea className="prompt" defaultValue={p}/><button className="btn primary" style={{marginTop:8}} onClick={()=>{navigator.clipboard.writeText(p);pop('프롬프트 복사됨')}}>Copy</button></div>)}</div></section>
  <section className={'page '+(page==='settings'?'active':'')}><div className="grid2"><Card title="GitHub" right={ghConfigured?'Connected':'Not configured'}><div className="note">`.env.local`에서 GITHUB_OWNER / GITHUB_REPO / GITHUB_BRANCH / GITHUB_TOKEN 설정. private repo token은 서버에서만 사용.</div></Card><Card title="Local Bridge" right="127.0.0.1 only"><div className="note">로컬 브리지의 <code>config.json</code>에 Master Path와 token을 넣고 실행. 브라우저에는 token을 Settings 입력값으로 저장.</div><BridgeToken onSave={()=>pop('브리지 토큰 저장됨')}/></Card></div><Card title="Google Calendar" right={calendar.state==='ready'||calendar.state==='empty'?'Connected':'Not connected'}><div className="note">GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET / GOOGLE_REFRESH_TOKEN / GOOGLE_CALENDAR_ID를 서버 환경변수로 설정. 현재 상태: {calendarStateText(calendar)}</div></Card></section>
  </main><div className={'toast '+(toast?'show':'')}>{toast}</div></div>
}
function Card({title,right,children}:{title:string,right?:string,children:React.ReactNode}){return <div className="card section"><div className="head"><h3>{title}</h3><span>{right}</span></div>{children}</div>}
function CalendarCard({title,events,calendar}:{title:string;events:CalendarEvent[];calendar:CalendarApiResponse}){return <Card title={title} right={calendar.state==='ready'?'Google Calendar':'Calendar'}>{events.length?events.map(event=><div className="event" key={event.id}><b>{event.title}</b><small>{formatCalendarEvent(event)} · {event.category}</small>{event.location&&<small>{event.location}</small>}</div>):<CalendarState calendar={calendar}/>}</Card>}
function CalendarState({calendar}:{calendar:CalendarApiResponse}){return <div className={calendar.state==='error'?'error':'empty'}>{calendarStateText(calendar)}</div>}
function calendarStateText(calendar:CalendarApiResponse){if(calendar.state==='unconfigured')return '.env.local에 Google Calendar 인증정보를 설정하세요.';if(calendar.state==='empty')return '오늘부터 향후 14일 안에 일정이 없습니다.';if(calendar.errorCode==='auth_error')return 'Calendar 인증이 만료되었거나 취소되었습니다. refresh token을 갱신하세요.';if(calendar.errorCode==='quota_error')return 'Google Calendar API quota를 확인하세요.';if(calendar.errorCode==='malformed_response')return 'Calendar 응답 형식을 확인할 수 없습니다.';if(calendar.state==='error')return 'Calendar 네트워크 연결을 확인하세요.';return '해당 일정이 없습니다.'}
function Kpi({label,value,sub}:{label:string,value:string,sub:string}){return <div className="card kpi"><small>{label}</small><strong>{value}</strong><span>{sub}</span></div>}
function Status({n,p}:{n:string,p:number}){return <div className="status"><span>{n}</span><div className="track"><div className="fill" style={{width:p+'%'}}/></div><b>{p}%</b></div>}
function ResultsPanel({dashboard}:{dashboard:DashboardBundle}){if(!dashboard.necessaryLabour||!dashboard.decomposition||!dashboard.validation)return <div className="card empty result-empty"><h3>결과 JSON을 사용할 수 없습니다</h3><p>{dashboard.error||'exporter를 실행하고 검증된 JSON을 GitHub에 반영하세요.'}</p><code>python exporter/export_results.py</code></div>;const levels=dashboard.necessaryLabour.series;const periods=dashboard.decomposition.periods;const maxLevel=Math.max(...levels.map(item=>item.value));const focus=periods.find(item=>item.period==='2015-2020')||periods[0];const contributions=[...focus.contributions].sort((a,b)=>Math.abs(b.totalChange)-Math.abs(a.totalChange)).slice(0,8);return <><div className="kpis">{levels.map(point=><Kpi key={point.year} label={String(point.year)} value={`${formatHours(point.value)}h`} sub={`${point.sourceCell} · 2020 prices`}/>) }<Kpi label="Validation" value={dashboard.validation.status.toUpperCase()} sub={`${dashboard.validation.checks.length} exporter checks`}/></div><div className="grid2 results-grid"><Card title="Necessary labour trend" right={dashboard.source}>{levels.map(point=><div className="result-bar" key={point.year}><span>{point.year}</span><div className="result-track"><div style={{width:`${point.value/maxLevel*100}%`}}/></div><b>{formatHours(point.value)}h</b></div>)}</Card><Card title="Period decomposition" right="hours"><table className="result-table"><thead><tr><th>Period</th><th>Change</th><th>Basket</th><th>Embodied labour</th></tr></thead><tbody>{periods.map(item=><tr key={item.period}><td>{item.period}</td><td>{signed(item.totalChange)}</td><td>{signed(item.basketEffect)}</td><td>{signed(item.embodiedLabourEffect)}</td></tr>)}</tbody></table></Card></div><div className="grid2 results-grid"><Card title={`Largest sector changes · ${focus.period}`} right="absolute rank"><table className="result-table"><thead><tr><th>Code</th><th>Sector</th><th>Change</th></tr></thead><tbody>{contributions.map(item=><tr key={item.code}><td>{item.code}</td><td>{item.name}</td><td>{signed(item.totalChange)}</td></tr>)}</tbody></table></Card><Card title="Exporter validation" right={dashboard.validation.scope}>{dashboard.validation.checks.map(check=><div className="validation-row" key={check.id}><b>{check.status.toUpperCase()}</b><span>{check.message}</span></div>)}<p className="muted validation-limit">{dashboard.validation.limitation}</p></Card></div><div className="note result-source">Source: <code>{dashboard.necessaryLabour.source.workbook}</code> · <code>{dashboard.decomposition.source.workbook}</code> · generated {formatDate(dashboard.validation.generatedAt)}</div></>}
function BridgeToken({onSave}:{onSave:()=>void}){const [v,setV]=useState('');useEffect(()=>setV(localStorage.getItem('thesisBridgeToken')||''),[]);return <div className="toolbar" style={{marginTop:10,marginBottom:0}}><input className="search" placeholder="Bridge token" value={v} onChange={e=>setV(e.target.value)}/><button className="btn" onClick={()=>{localStorage.setItem('thesisBridgeToken',v);onSave()}}>Save</button></div>}
function basename(p:string){return p.split('/').pop()||p} function ext(p:string){const e=(p.split('.').pop()||'FILE').toUpperCase();return e.slice(0,4)} function formatDate(s:string){if(!s)return '';try{return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(s))}catch{return s}} function formatCalendarEvent(event:CalendarEvent){if(event.allDay)return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'short',day:'numeric'}).format(new Date(`${event.start}T00:00:00+09:00`));return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(event.start))} function formatHours(n:number){return n.toLocaleString('ko-KR',{minimumFractionDigits:2,maximumFractionDigits:2})} function signed(n:number){return `${n>=0?'+':''}${formatHours(n)}`}
